"""
Generates an optimized Naukri headline and profile summary using Groq AI.
Content is sourced from config/profile_content.py.

Strict limits enforced both in the prompt and in code:
  - Headline : max 250 characters
  - Summary  : max 1000 characters
"""

import json
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

_HEADLINE_LIMIT = 250
_SUMMARY_LIMIT  = 1000

_SYSTEM_PROMPT = """\
You are an expert Naukri.com profile optimizer. Your goal is to help a software engineer \
rank higher in Naukri recruiter searches and get more interview calls.

You will be given:
- The candidate's current headline and summary (what is live on Naukri right now)
- Full profile details (experience, skills, projects, achievements)

Your task: generate a FRESH headline and summary that are strictly better than the current ones.

RULES:
- Do NOT repeat or closely paraphrase the current headline or summary — generate something new
- No fabricated numbers, percentages, or metrics not present in the profile
- No filler phrases: "passionate about", "enthusiastic", "team player", "results-driven"

HEADLINE (max {headline_limit} characters — hard limit, never exceed):
- Use | as separator between segments
- Pack recruiter-searchable keywords: role, top frameworks, specialisation, experience
- Must be immediately scannable — every word must earn its place
- Vary structure from the current headline

SUMMARY (max {summary_limit} characters — hard limit, never exceed):
- First person, no bullet points, no headers
- Open with a sharp 1-line hook that positions the candidate uniquely
- Cover: core stack, standout achievements, AI-augmented development angle, what they deliver
- End with what kind of role/team they add value to
- Dense with Naukri search keywords (React.js, Next.js, Node.js, React Native, TypeScript, etc.)
- Must read differently from the current summary

RESPONSE FORMAT — return ONLY valid JSON, nothing else:
{{
  "headline": "...",
  "summary": "..."
}}
"""


def generate_headline_and_summary(
    current_headline: str = "",
    current_summary: str = "",
) -> tuple[str, str]:
    """Return (headline, summary) generated by AI, both within character limits.

    current_headline / current_summary: live values scraped from Naukri — fed to the
    AI so it generates something fresh rather than repeating existing content.
    Raises RuntimeError if generation fails or limits are breached after trimming.
    """
    import httpx

    _bootstrap_env()
    from config.settings import GROQ_API_KEY
    from config.profile_content import (
        NAME, EXPERIENCE, SKILLS, PROJECTS, ACHIEVEMENTS, TOTAL_EXPERIENCE_YEARS
    )

    if not GROQ_API_KEY:
        raise RuntimeError("GROQ_API_KEY is not set in .env")

    current_block = ""
    if current_headline or current_summary:
        current_block = f"""
CURRENT HEADLINE ON NAUKRI (do not repeat this):
{current_headline or '(not available)'}

CURRENT SUMMARY ON NAUKRI (do not repeat this):
{current_summary or '(not available)'}
""".strip()

    profile_block = f"""
{current_block}

CANDIDATE: {NAME}
TOTAL EXPERIENCE: {TOTAL_EXPERIENCE_YEARS}

WORK EXPERIENCE:
{EXPERIENCE.strip()}

TECHNICAL SKILLS:
{SKILLS.strip()}

KEY PROJECTS:
{PROJECTS.strip()}

ACHIEVEMENTS & CERTIFICATIONS:
{ACHIEVEMENTS.strip()}
""".strip()

    prompt = _SYSTEM_PROMPT.format(
        headline_limit=_HEADLINE_LIMIT,
        summary_limit=_SUMMARY_LIMIT,
    )

    logger.info("Generating optimized Naukri headline and summary via Groq AI...")
    response = httpx.post(
        "https://api.groq.com/openai/v1/chat/completions",
        headers={
            "Authorization": f"Bearer {GROQ_API_KEY}",
            "Content-Type": "application/json",
        },
        json={
            "model": "llama-3.3-70b-versatile",
            "messages": [
                {"role": "system", "content": prompt},
                {"role": "user", "content": profile_block},
            ],
            "temperature": 0.4,
            "max_tokens": 1024,
            "response_format": {"type": "json_object"},
        },
        timeout=60,
    )
    response.raise_for_status()

    raw = response.json()["choices"][0]["message"]["content"].strip()
    data = json.loads(raw)

    headline = data.get("headline", "").strip()
    summary  = data.get("summary", "").strip()

    # Hard-enforce limits in code — never trust the model alone
    if len(headline) > _HEADLINE_LIMIT:
        logger.warning("Headline exceeded %d chars (%d) — trimming", _HEADLINE_LIMIT, len(headline))
        headline = headline[:_HEADLINE_LIMIT].rsplit("|", 1)[0].strip()

    if len(summary) > _SUMMARY_LIMIT:
        logger.warning("Summary exceeded %d chars (%d) — trimming", _SUMMARY_LIMIT, len(summary))
        summary = summary[:_SUMMARY_LIMIT].rsplit(".", 1)[0].strip() + "."

    logger.info("Headline (%d chars): %s", len(headline), headline)
    logger.info("Summary  (%d chars): %s", len(summary), len(summary))

    return headline, summary


def _bootstrap_env():
    project_root = str(Path(__file__).parent.parent.parent)
    import sys
    if project_root not in sys.path:
        sys.path.insert(0, project_root)
    from dotenv import load_dotenv
    load_dotenv(Path(project_root) / ".env")
